[build]
  command = "quarto render"
  publish = "_site"

[build.environment]
  QUARTO_VERSION = "1.5.56"

[build.lifecycle]
  # This makes sure Quarto is installed before build
  onBuild = """
  curl -L https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.tar.gz -o quarto.tar.gz
  tar -xzf quarto.tar.gz
  mv quarto-${QUARTO_VERSION} /opt/buildhome/quarto
  export PATH=/opt/buildhome/quarto/bin:$PATH
  quarto render
  """

